/*-------------------------- 2017-------------------------*/
/*NOMBRE	TEMPORADA	DESCRIPCION	NOTA	CAPITULOS*/
insert into ANIMES VALUES("Zero kara hajimeru mahou no sho","1","Bruja rengar blanco","10"," 8");
insert into ANIMES VALUES("Rokudenashi majutsu koushi to akashic records","1","Best uniforme of anime","10"," 8");
insert into ANIMES VALUES("Oushitsu kyoushi Haine","1",	"Tutor real"," 9"," 7");
insert into ANIMES VALUES("Saenai heroine no sodatekata 2","2",	"Crear juego"," 8","12");
insert into ANIMES VALUES("Clockwork Planet","1","Mundo de relojes","10","12");
insert into ANIMES VALUES("Shingeki no kyojin 2","2","Mikasa","10","12");
insert into ANIMES VALUES("Boku no hero 2","2","All Might","10","12");
insert into ANIMES VALUES("Eromanga-sensei","1","Hermana dibuja ero"," 9","12");
insert into ANIMES VALUES("Re:Creators","1","Fuera de su anime"," 7","12");
insert into ANIMES VALUES("Alice to Zoroku","1","lolis poderes","10","12");
insert into ANIMES VALUES("Busou shoujo machiavellianism","1","peli verde super kawaii","10","12");
insert into ANIMES VALUES("Accel World","1","Prota cerdito"," 7","12");
insert into ANIMES VALUES("Akame ga kill","1","Prota no es prota"," 7","12");
insert into ANIMES VALUES("Aho Girl","1","Loca platanos"," 8","1");
insert into ANIMES VALUES("Tsurezure Children","1","Declaraciones"," 7","1");
insert into ANIMES VALUES("Isekai Shoukudou","1","Restaurante universal","7","1");
insert into ANIMES VALUES("Koi to Uso","1","Amor prohibido","9","1");
insert into ANIMES VALUES("Keppeki Danshi! Aoyama-kun","1","Futbolista limpiador","8","1");
insert into ANIMES VALUES("Kakegurui","1","Copia no game no life","8","1");
insert into ANIMES VALUES("Akiba`s strip","1","Quitar ropa para ganar"," 8","12");
insert into ANIMES VALUES("Angel Beats","1","Loli programadora"," 8","12");
insert into ANIMES VALUES("Another","1","Chica parche","10","12");
insert into ANIMES VALUES("Assassination Classroom","1","Koro-sensei"," 9","24");
insert into ANIMES VALUES("Assassination Classroom 2","2","Koro-sensei"," 8","24");
insert into ANIMES VALUES("Baby princess 3d","1","harem 1 capitulo"," 7"," -1");
insert into ANIMES VALUES("Black Bullet","1","lolis para todos"," 7"," 1");
insert into ANIMES VALUES("Boku dake ga inai machi","1","Volver al pasado"," 9"," 1");
insert into ANIMES VALUES("Boku no hero","1","All Might","10","12");
insert into ANIMES VALUES("Charlotte","1","Chicos con poderes",	" 8","13");
insert into ANIMES VALUES("Choujingen game neptune","1","Diosas lolis","10","13");
insert into ANIMES VALUES("Date a live","1","Preguntas"," 7","12");
insert into ANIMES VALUES("Date a live 2","2","Kurumi"," 8","12");
insert into ANIMES VALUES("Death parade","1","Pruebas muerte"," 9","12");
insert into ANIMES VALUES("Kono subarashii","1","Diosa inutil","10","10");
insert into ANIMES VALUES("Kono subarashii 2","2","Rival megumi","10","10");
insert into ANIMES VALUES("Gabriel Dropout","1","Ángel caido","7","12");
insert into ANIMES VALUES("Watamote","1","Chica Hikikiomori","9","12");
insert into ANIMES VALUES("Valkyrie Drive","1","Chicas isla","8","12");
insert into ANIMES VALUES("Kiss x sis","1","Hermanas","9","12");
insert into ANIMES VALUES("Kono Naka","1","Hermana sorpresa","7","12");
insert into ANIMES VALUES("One Punch Man","1","Saitama","10","12");
insert into ANIMES VALUES("Monster Musume","1","suu","10","12");
insert into ANIMES VALUES("Overloard","1","Atrapado en un juego","9","13");
insert into ANIMES VALUES("Sakamoto","1","PUTO AMO","7","12");
insert into ANIMES VALUES("Kabaneri","1","zombies titanes","10","13");
insert into ANIMES VALUES("Kiniro Mosaic","1","Karen desu","8","12");
insert into ANIMES VALUES("Dagashi Kashi","1","Loca de los dulces","7","12");
insert into ANIMES VALUES("Trinity Seven","1","No princeso","8","12");
insert into ANIMES VALUES("Sword art online","1","Kirito","8","25");
insert into ANIMES VALUES("Sword art online 2","2","Kirito","4","24");
insert into ANIMES VALUES("Shimoneta","1","agujero misterioso","8","12");
insert into ANIMES VALUES("Sankarea","1","Novia Zombie","6","12");
insert into ANIMES VALUES("Mirai Nikki","1","yuki yuki","10","26");
insert into ANIMES VALUES("Rewrite","1","oppais oculto","10","13");
insert into ANIMES VALUES("Rewrite:Moon and terra","2","oppais oculto","10","11");
insert into ANIMES VALUES("Re:Zero","1","Rem Rem","10","25");
insert into ANIMES VALUES("Rampo Kitan: Game of Laplace","1","Calculo matemático","8","11");
insert into ANIMES VALUES("Outbreak Company","1","Reina loli","8","12");
insert into ANIMES VALUES("Punchline","1","Gemidos","7","12");
insert into ANIMES VALUES("Prison school","1","Carcel","10","12");
insert into ANIMES VALUES("Machine Doll wa Kizutsukanai","1","Waifu","8","12");
insert into ANIMES VALUES("Noragami","1","Dios pobre","9","12");
insert into ANIMES VALUES("Noragami Aragoto","2","Dios pobre","8","13");
insert into ANIMES VALUES("Osomatsu-san","1","Novita","10","25");
insert into ANIMES VALUES("Sakura-so no Pet na Kanojo","1","Sakura-so","10","24");
insert into ANIMES VALUES("Seirei Tsukai no Bladedance","1","loli de fuego","10","12");
insert into ANIMES VALUES("No Game No Life","1","Shiro y Sora","10","12");
insert into ANIMES VALUES("Netoge no Yome wa Onna","1","Ako","8","12");

/*----------------------POR METER EN LAS OTRAS TABLAS--------------------*/

insert into ANIMES VALUES("Ore ga Ojo-sama Gakko","1","Musculos","8","12");
insert into ANIMES VALUES("Yamada-kun to 7-nin no Majo","1","Besos con brujas","9","12");
insert into ANIMES VALUES("Plastic Nee-san","1","Serie corta","9","12");
insert into ANIMES VALUES("Shokugeki no Soma","1","Cocina","10","24");
insert into ANIMES VALUES("Shokugeki no Souma: Ni no Sara","2","Cocina","9","13");
insert into ANIMES VALUES("Kuroko no basket","1","Baloncesto","10","25");
insert into ANIMES VALUES("Kuroko no basket 2","2","Baloncesto","10","25");
insert into ANIMES VALUES("Kuroko no basket 3","3","Baloncesto","10","25");
insert into ANIMES VALUES("Shingeki no Kyojin","1","Titanes","10","25");
insert into ANIMES VALUES("High School DxD","1","Rias Gremory","10","12");
insert into ANIMES VALUES("High School DxD New","2","Rias Gremory","10","12");
insert into ANIMES VALUES("High School DxD Born","3","Rias Gremory","10","13");
insert into ANIMES VALUES("Dakara Boku wa, H ga Dekinai","1","hermano issei","7","12");
insert into ANIMES VALUES("Tokyo Ghoul","1","Comer humanos","9","12");
insert into ANIMES VALUES("Hai to Gensou no Grimgar","1","Bichos sufren","9","12");
insert into ANIMES VALUES("Hentai Oji to Warawanai Neko","1","Gato suerte","8","12");
insert into ANIMES VALUES("Kore wa Zombie Desu ka? of the dead","2","Yuu","7","12");
insert into ANIMES VALUES("School-Live!","1","Zombies vs Lolis","9","12");
insert into ANIMES VALUES("Gakusen Toshi Asterisk","1","Escuela de pelea","8","12");
insert into ANIMES VALUES("Gakusen Toshi Asterisk 2","2","Escuela de pelea","9","13");
insert into ANIMES VALUES("Boku wa Tomodachi ga Sukunai","1","Club de los vecinos","8","12");
insert into ANIMES VALUES("Boku wa Tomodachi ga Sukunai next","2","Club de los vecinos","8","12");
insert into ANIMES VALUES("Sora no otoshimono","1","Angeles","8","12");
insert into ANIMES VALUES("Sora no otoshimono:Forte","2","Angeles","8","12");
insert into ANIMES VALUES("Shinmai Maou no Testament","1","Como DxD","7","13");
insert into ANIMES VALUES("Shinmai Maou no Testament Burst","2","Como DxD","7","11");
insert into ANIMES VALUES("Saenai heroine no sodatekata","1","Crear juego"," 10","13");
insert into ANIMES VALUES("Masamune-kun no Revenge","1","Venganza por amor"," 8","12");
insert into ANIMES VALUES("Selector infected","1","Juego de cartas"," 9","12");
insert into ANIMES VALUES("Selector Spread Wixoss","2","Juego de cartas"," 8","12");
insert into ANIMES VALUES("Lostorage incited Wixoss","3","Juego de cartas"," 8","12");
insert into ANIMES VALUES("Highschool of the dead","1","Zombies"," 9","12");
insert into ANIMES VALUES("Himouto! Umaru-chan","1","hamster"," 9","12");
insert into ANIMES VALUES("Urara Meirocho","1","Road to bruja"," 7","12");
insert into ANIMES VALUES("Musaigen no Phantom World","1","Mundo con poderes"," 6","13");
insert into ANIMES VALUES("Lance N' Masques","1","Caballeros"," 8","12");
insert into ANIMES VALUES("Haruchika","1","Chica flauta detective"," 7","12");
insert into ANIMES VALUES("Mob Psycho 100","1","guiños saitama"," 7","12");
insert into ANIMES VALUES("Denpa Onna to Seishun Otoko","1","Chica ovni"," 8","12");
insert into ANIMES VALUES("Boruto","1","Naruto falso"," 6","12");
insert into ANIMES VALUES("Chunibyo Demo Koi ga Shitai!","1","Ojo malvado"," 8","12");
insert into ANIMES VALUES("Chunibyo Demo Koi ga Shitai Ren!","2","Ojo malvado"," 7","12");
insert into ANIMES VALUES("Flip Flappers","1","Ojos grandes"," 7","12");
insert into ANIMES VALUES("Kuzu no Honkai","1","Amigos con derecho"," 9","12");
insert into ANIMES VALUES("Okami-san to Shichinin no Nakama-tachi","1","Favor por favor"," 7","12");
insert into ANIMES VALUES("Dragon ball","1","koku niño"," 7","153");
insert into ANIMES VALUES("Dragon ball Z","2","Koku saiyan"," 9","291");
insert into ANIMES VALUES("Dragon ball super","3","Koku dios"," 8","100");
insert into ANIMES VALUES("Dragon ball GT","4","Koku niño 2"," 6","64");
insert into ANIMES VALUES("Little Witch Academia","1","Road to bruja"," 10","24");
insert into ANIMES VALUES("Nagi no Asukara","1","Amor bajo el agua"," 8","26");
