insert into FECHA VALUES("Zero kara hajimeru mahou no sho","Abril","En emision","Primavera","2017","Lunes");
insert into FECHA VALUES("Rokudenashi majutsu koushi to akashic records","Abril","En emision","Primavera","2017","Martes");
insert into FECHA VALUES("Oushitsu kyoushi Haine","Abril","En emision","Primavera","2017","Martes");
insert into FECHA VALUES("Saenai heroine no sodatekata 2","Abril","En emision","Primavera","2017","Jueves");
insert into FECHA VALUES("Clockwork Planet","Abril","En emision","Primavera","2017","Jueves");
insert into FECHA VALUES("Shingeki no kyojin 2","Abril","En emision","Primavera","2017","Sabado");
insert into FECHA VALUES("Boku no hero 2","Abril","En emision","Primavera","2017","Sabado");
insert into FECHA VALUES("Eromanga-sensei","Abril","En emision","Primavera","2017","Sabado");
insert into FECHA VALUES("Re:Creators","Abril","En emision","Primavera","2017","Sabado");
insert into FECHA VALUES("Alice to Zoroku","Abril","En emision","Primavera","2017","Sabado");
insert into FECHA VALUES("Busou shoujo machiavellianism","Abril","En emision","Primavera","2017","Domingo");
insert into FECHA VALUES("Accel World","Abril","Septiembre","Primavera","2012","Finalizado");
insert into FECHA VALUES("Akame ga kill","Julio","Diciembre","Verano","2014","Finalizado");
insert into FECHA VALUES("Aho Girl","Junio","En emision","Verano","2017","Martes");
insert into FECHA VALUES("Tsurezure Children","Junio","En emision","Verano","2017","Martes");
insert into FECHA VALUES("Isekai Shoukudou","Junio","En emision","Verano","2017","Lunes");
insert into FECHA VALUES("Koi to Uso","Junio","En emision","Verano","2017","Lunes");
insert into FECHA VALUES("Keppeki Danshi! Aoyama-kun","Junio","En emision","Verano","2017","Domingo");
insert into FECHA VALUES("Kakegurui","Junio","En emision","Verano","2017","Sabado");
insert into FECHA VALUES("Akiba`s strip","Enero","Marzo","Invierno","2016","Miercoles");
insert into FECHA VALUES("Angel Beats","Abril","Junio","Primavera","2010","Sabado");
insert into FECHA VALUES("Another","Enero","Marzo","Invierno","2011","Lunes");
insert into FECHA VALUES("Assassination Classroom","Enero","Junio","Invierno","2014","Viernes");
insert into FECHA VALUES("Assassination Classroom 2","Enero","Junio","Invierno","2015","Jueves");
insert into FECHA VALUES("Baby princess 3d","Julio","Julio","Verano","2011","Miercoles");
insert into FECHA VALUES("Black Bullet","Abril","Julio","Primavera","2014","Martes");
insert into FECHA VALUES("Boku dake ga inai machi","Enero","Marzo","Invierno","2015","Viernes");
insert into FECHA VALUES("Boku no hero","Abril","Junio","Primavera","2016","Domingo");
insert into FECHA VALUES("Charlotte","Julio","Septiembre","Verano","2015","Sabado");
insert into FECHA VALUES("Choujingen game neptune","Julio","Septiembre","Verano","2013","Viernes");
insert into FECHA VALUES("Date a live","Abril","Junio","Primavera","2013","Sabado");
insert into FECHA VALUES("Date a live 2","Abril","Junio","Primavera","2014","Sabado");
insert into FECHA VALUES("Death parade","Enero","Marzo","Invierno","2014","Viernes");
insert into FECHA VALUES("Kono subarashii","Enero","Marzo","Invierno","2015","Miercoles");
insert into FECHA VALUES("Kono subarashii 2","Enero","Marzo","Invierno","2016","Jueves");
insert into FECHA VALUES("Gabriel Dropout","Enero","Marzo","Invierno","2016","Lunes");
insert into FECHA VALUES("Watamote","Julio","Septiembre","Verano","2013","Lunes");
insert into FECHA VALUES("Valkyrie Drive","Octubre","Diciembre","Otoño","2015","Sabado");
insert into FECHA VALUES("Kiss x sis","Abril","Junio","Primavera","2010","Domingo");
insert into FECHA VALUES("Kono Naka","Julio","Septiembre","Verano","2012","Viernes");
insert into FECHA VALUES("One Punch Man","Octubre","Diciembre","Otoño","2015","Lunes");
insert into FECHA VALUES("Monster Musume","Julio","Septiembre","Verano","2015","Martes");
insert into FECHA VALUES("Overloard","Julio","Septiembre","Verano","2015","Martes");
insert into FECHA VALUES("Sakamoto","Abril","Julio","Primavera","2016","Viernes");
insert into FECHA VALUES("Kabaneri","Abril","Junio","Primavera","2016","Viernes");
insert into FECHA VALUES("Kiniro Mosaic","Julio","Septiembre","Verano","2013","Sabado");
insert into FECHA VALUES("Dagashi Kashi","Enero","Marzo","Invierno","2016","Jueves");
insert into FECHA VALUES("Trinity Seven","Octubre","Diciembre","Otoño","2014","Martes");
insert into FECHA VALUES("Sword art online","Julio","Diciembre","Verano","2012","Sabado");
insert into FECHA VALUES("Sword art online 2","Julio","Diciembre","Verano","2014","Sabado");
insert into FECHA VALUES("Shimoneta","Julio","Septiembre","Verano","2015","Sabado");
insert into FECHA VALUES("Sankarea","Abril","Junio","Primavera","2012","Jueves");
insert into FECHA VALUES("Mirai Nikki","Octubre","Abril","Otoño","2011","Domingo");
insert into FECHA VALUES("Rewrite","Julio","Septiembre","Verano","2016","Sabado");
insert into FECHA VALUES("Rewrite:Moon and terra","Enero","Marzo","Invierno","2016","Sabado");
insert into FECHA VALUES("Re:Zero","Abril","Septiembre","Primavera","2016","Lunes");
insert into FECHA VALUES("Rampo Kitan: Game of Laplace","Enero","Septiembre","Verano","2015","Jueves");
insert into FECHA VALUES("Outbreak Company","Octubre","Diciembre","Otoño","2013","Jueves");
insert into FECHA VALUES("Punchline","Abril","Junio","Primavera","2015","Jueves");
insert into FECHA VALUES("Prison school","Julio","Septiembre","Verano","2015","Viernes");
insert into FECHA VALUES("Machine Doll wa Kizutsukanai","Octubre","Diciembre","Otoño","2013","Lunes");
insert into FECHA VALUES("Noragami","Octubre","Diciembre","Otoño","2015","Viernes");
insert into FECHA VALUES("Noragami Aragoto","Octubre","Diciembre","Otoño","2015","Sabado");
insert into FECHA VALUES("Osomatsu-san","Octubre","Marzo","Otoño","2015","Domingo");
insert into FECHA VALUES("Sakura-so no Pet na Kanojo","Octubre","Marzo","Otoño","2012","Martes");
insert into FECHA VALUES("Seirei Tsukai no Bladedance","Julio","Septiembre","Verano","2014","Lunes");
insert into FECHA VALUES("No game No Life","Abril","Junio","Primavera","2014","Miercoles");
insert into FECHA VALUES("Netoge no Yome wa Onna","Abril","Junio","Primavera","2016","Jueves");

/*----------------------POR METER EN LAS OTRAS TABLAS--------------------*/

/*insert into FECHA VALUES("NOMBRE","MES","MES","TEMPORADA","AÑO";"DIA");*/
