DROP DATABASE IF EXISTS METEO;

CREATE DATABASE METEO;

USE METEO;

DROP TABLE IF EXISTS CIUDAD ;

CREATE TABLE CIUDAD (

	CODIGO varchar (5) NOT NULL,
	NOMBRE varchar (20) NOT NULL,
	PRIMARY KEY (CODIGO)	

);

INSERT INTO CIUDAD

	VALUES('12345','Fernando');

INSERT INTO CIUDAD

	VALUES('12352','SILVA');

INSERT INTO CIUDAD

	VALUES('12323','XAVIER');


DROP TABLE IF EXISTS TEMPERATURA ;

CREATE TABLE TEMPERATURA (

	DIA DATE NOT NULL,
	CODIGO_CIUDAD varchar (20) NOT NULL,
	GRADOS varchar (5) NOT NULL,
	PRIMARY KEY(DIA),
	FOREIGN KEY (CODIGO_CIUDAD)
		REFERENCES CIUDAD(CODIGO)
		ON UPDATE CASCADE ON DELETE CASCADE

);

INSERT INTO TEMPERATURA

	VALUES('1996/01/06','12345','50º');

INSERT INTO TEMPERATURA

	VALUES('1998/01/09','12345','60º');

INSERT INTO TEMPERATURA

	VALUES('2017/08/08','12345','70º');



DROP TABLE IF EXISTS HUMEDAD ;

CREATE TABLE HUMEDAD (

	DIA DATE NOT NULL,
	CODIGO_CIUDAD varchar (20) NOT NULL,
	PORCENTAJE varchar (5) NOT NULL,
	PRIMARY KEY(DIA),
	FOREIGN KEY (CODIGO_CIUDAD) 
		REFERENCES CIUDAD  (CODIGO)
		ON UPDATE CASCADE ON DELETE CASCADE

);


INSERT INTO HUMEDAD

	VALUES('1996/01/06','12345','50%');

INSERT INTO HUMEDAD

	VALUES('1998/01/06','12345','30%');

INSERT INTO HUMEDAD

	VALUES('2017/07/07','12345','20%');


DROP TABLE IF EXISTS INFORME ;

CREATE TABLE INFORME (

	ID INTEGER (5) auto_increment NOT NULL,
	DIA DATE NOT NULL,
	CODIGO_CIUDAD varchar (20) NOT NULL,
	PRIMARY KEY (ID,DIA),
	FOREIGN KEY (CODIGO_CIUDAD)
		REFERENCES CIUDAD(CODIGO)
		ON UPDATE CASCADE ON DELETE CASCADE




);


INSERT INTO INFORME(DIA,CODIGO_CIUDAD)

	VALUES('2016/04/04','12345');

INSERT INTO INFORME(DIA,CODIGO_CIUDAD)


	VALUES('2017/05/05','12345');

INSERT INTO INFORME(DIA,CODIGO_CIUDAD)

	VALUES('2011/11/11','12345');


