DROP DATABASE IF EXISTS PHONE_HOUSE;

CREATE DATABASE PHONE_HOUSE;

USE PHONE_HOUSE;

DROP TABLE IF EXISTS CLIENTES;

CREATE TABLE CLIENTES(

	DNI CHAR(9) NOT NULL,
	Nombre VARCHAR(20) NOT NULL,
	Apellidos VARCHAR(20) NOT NULL,
	Telefono INTEGER(9) NOT NULL,
	Email VARCHAR(30) NOT NULL,
	PRIMARY KEY(DNI)

);

DROP TABLE IF EXISTS TIENDAS;

CREATE TABLE TIENDAS(

	Nombre VARCHAR(20) NOT NULL, 
	Provincia VARCHAR(20) NOT NULL,
	Localidad VARCHAR(20) NOT NULL,
	Direccion VARCHAR(50) NOT NULL,
	Telefono INTEGER (9) NOT NULL,
	DiaApertura SET ('Lunes','Martes','Miercoles','Jueves','Vieres','Sabado') NOT NULL,
	DiaCierre ENUM ('Sabado','Domingo') NOT NULL DEFAULT 'Domingo',
	HoraApertura TIME NOT NULL ,
	HoraCierra TIME NOT NULL,
	PRIMARY KEY(Nombre)


);


DROP TABLE IF EXISTS OPERADORAS;

CREATE TABLE OPERADORAS(

	Nombre VARCHAR(20) NOT NULL,
	ColorLogo VARCHAR (20) NOT NULL,
	PorcentajeCobertura VARCHAR(10) NOT NULL,
	FrecuenciaGSM VARCHAR(10) NOT NULL,
	PaginaWeb VARCHAR(20) NOT NULL,
	PRIMARY KEY (Nombre)

);


DROP TABLE IF EXISTS TARIFAS;

CREATE TABLE TARIFAS(

	Nombre VARCHAR(20) NOT NULL,
	Nombre_OPERADORAS VARCHAR (20) NOT NULL,
	TamañoDatos VARCHAR(20) NOT NULL,
	TipoDatos VARCHAR(20) NOT NULL,
	MinutosGratis VARCHAR(20) NOT NULL,
	SMSGratis VARCHAR(20) NOT NULL,
	PRIMARY KEY(Nombre),
	FOREIGN KEY (Nombre_OPERADORAS)
		REFERENCES OPERADORAS(Nombre)


);
