DROP DATABASE IF EXISTS PHONE_HOUSE;

CREATE DATABASE PHONE_HOUSE;

USE PHONE_HOUSE;

DROP TABLE IF EXISTS CLIENTES;

CREATE TABLE CLIENTES(

	DNI CHAR(9) NOT NULL,
	Nombre VARCHAR(20) NOT NULL,
	Apellidos VARCHAR(20) NOT NULL,
	Telefono INTEGER(9) NOT NULL,
	Email VARCHAR(30) NOT NULL,
	PRIMARY KEY(DNI)

);

DROP TABLE IF EXISTS TIENDAS;

CREATE TABLE TIENDAS(

	Nombre VARCHAR(20) NOT NULL, 
	Provincia VARCHAR(20) NOT NULL,
	Localidad VARCHAR(20) NOT NULL,
	Direccion VARCHAR(50) NOT NULL,
	Telefono INTEGER (9) NOT NULL,
	DiaApertura SET ('Lunes','Martes','Miercoles','Jueves','Vieres','Sabado') NOT NULL,
	DiaCierre ENUM ('Sabado','Domingo') NOT NULL DEFAULT 'Domingo',
	HoraApertura TIME NOT NULL ,
	HoraCierra TIME NOT NULL,
	PRIMARY KEY(Nombre)


);


DROP TABLE IF EXISTS OPERADORAS;

CREATE TABLE OPERADORAS(

	Nombre VARCHAR(20) NOT NULL,
	ColorLogo VARCHAR (20) NOT NULL,
	PorcentajeCobertura VARCHAR(10) NOT NULL,
	FrecuenciaGSM VARCHAR(10) NOT NULL,
	PaginaWeb VARCHAR(20) NOT NULL,
	PRIMARY KEY (Nombre)

);


DROP TABLE IF EXISTS TARIFAS;

CREATE TABLE TARIFAS(

	Nombre VARCHAR(20) NOT NULL,
	Nombre_OPERADORAS VARCHAR (20) NOT NULL,
	TamañoDatos VARCHAR(20) NOT NULL,
	TipoDatos VARCHAR(20) NOT NULL,
	MinutosGratis VARCHAR(20) NOT NULL,
	SMSGratis VARCHAR(20) NOT NULL,
	PRIMARY KEY(Nombre),
	FOREIGN KEY (Nombre_OPERADORAS)
		REFERENCES OPERADORAS(Nombre)

);

DROP TABLE IF EXISTS MOVILES;

CREATE TABLE MOVILES(

	Marca VARCHAR(20) NOT NULL,
	Modelo VARCHAR(20) NOT NULL,
	Descripcion VARCHAR(30) NOT NULL,
	SO VARCHAR(20) NOT NULL,
	RAM VARCHAR(20) NOT NULL,
	PulgadasPantalla VARCHAR(20) NOT NULL,
	CamaraMpx VARCHAR(20) NOT NULL,
	PRIMARY KEY(Marca,Modelo)

);

DROP TABLE IF EXISTS MOVIL_LIBRE;

CREATE TABLE MOVIL_LIBRE(

	Marca_Moviles VARCHAR(20) NOT NULL,
	Modelo_Moviles VARCHAR(20) NOT NULL,
	precio INTEGER NOT NULL,
	FOREIGN KEY (Marca_Moviles,Modelo_Moviles)
		REFERENCES MOVILES(Marca,Modelo)
		ON UPDATE CASCADE ON DELETE CASCADE


);

DROP TABLE IF EXISTS MOVIL_CONTRATO;

CREATE TABLE MOVIL_CONTRATO(

	Marca_Moviles VARCHAR(20) NOT NULL,
	Modelo_Moviles VARCHAR(20) NOT NULL,
	Nombre_OPERADORAS VARCHAR(20) NOT NULL,
	precio INTEGER NOT NULL,
	FOREIGN KEY (Marca_Moviles,Modelo_Moviles)
		REFERENCES MOVILES(Marca,Modelo)
		ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (Nombre_OPERADORAS)
		REFERENCES OPERADORAS(Nombre)
		ON UPDATE CASCADE ON DELETE CASCADE

);

DROP TABLE IF EXISTS OFERTAS;

CREATE TABLE OFERTAS(

	Nombre_OPERADORAS_TARIFAS VARCHAR(20) NOT NULL,
	Nombre_TARIFAS VARCHAR(20) NOT NULL,
	Marca_Movil_CONTRATO VARCHAR(20) NOT NULL,
	Modelo_MOVIL_CONTRATO VARCHAR(20) NOT NULL,
	FOREIGN KEY (Nombre_OPERADORAS_TARIFAS,Nombre_TARIFAS)
		REFERENCES TARIFAS(Nombre_OPERADORAS,Nombre),

	FOREIGN KEY (Marca_Movil_CONTRATO,Modelo_MOVIL_CONTRATO)
		REFERENCES MOVIL_CONTRATO(Marca_Moviles,Modelo_Moviles)

);




