DROP DATABASE IF EXISTS TIEMPO;

CREATE DATABASE TIEMPO;

USE TIEMPO;

DROP TABLE IF EXISTS CIUDAD;

	CREATE TABLE CIUDAD(

	codigo integer(5) NOT NULL,
	nombre varchar(20) NOT NULL,
	PRIMARY KEY(CODIGO)
	
);

INSERT INTO CIUDAD

	VALUES ('12345','Fernando');

INSERT INTO CIUDAD

	VALUES ('12387','Clauida');

INSERT INTO CIUDAD

	VALUES ('12350','Rem');

	

DROP TABLE IF EXISTS TEMPERATURA;

	CREATE TABLE TEMPERATURA(

	dia DATE NOT NULL,
	codigo_CIUDAD integer(5) NOT NULL,
	grados varchar(20) NOT NULL,
	PRIMARY KEY(dia),
	FOREIGN KEY (codigo_CIUDAD)
		REFERENCES CIUDAD(codigo)
		ON UPDATE CASCADE ON DELETE CASCADE
	
);

INSERT INTO TEMPERATURA

	VALUES ('1996/01/06','12345','50º');

INSERT INTO TEMPERATURA

	VALUES ('1999/01/06','12345','50º');

INSERT INTO TEMPERATURA

	VALUES ('2001/01/06','12345','50º');




DROP TABLE IF EXISTS HUMEDAD;

	CREATE TABLE HUMEDAD(

	dia DATE NOT NULL,
	codigo_CIUDAD integer(5) NOT NULL,
	porcentaje varchar(20) NOT NULL,
	PRIMARY KEY(dia),
	FOREIGN KEY (codigo_CIUDAD)
		REFERENCES CIUDAD(codigo)
		ON UPDATE CASCADE ON DELETE CASCADE
	
);

INSERT INTO HUMEDAD

	VALUES ('1996/01/06','12345','50%');

INSERT INTO HUMEDAD

	VALUES ('1999/01/06','12345','50%');

INSERT INTO HUMEDAD

	VALUES ('2001/01/06','12345','50%');




DROP TABLE IF EXISTS INFORME;

	CREATE TABLE INFORME(

	id integer NOT NULL auto_increment,
	dia DATE NOT NULL,
	codigo_CIUDAD integer(5) NOT NULL,
	PRIMARY KEY(id,dia),
	FOREIGN KEY (codigo_CIUDAD)
		REFERENCES CIUDAD(codigo)
		ON UPDATE CASCADE ON DELETE CASCADE
	
);


INSERT INTO INFORME (dia,codigo_CIUDAD)

	VALUES ('1996/01/06','12345');
	
INSERT INTO INFORME (dia,codigo_CIUDAD)

	VALUES ('1999/01/06','12345');
	
