insert into characters VALUES("Mujer","Zero kara hajimeru mahou no sho","Zero","Blanco","no",NULL, "zero");
insert into characters VALUES("Mujer","Zero kara hajimeru mahou no sho","Albus","Rubio","no",NULL, "albus");
insert into characters VALUES("Mujer","Rokudenashi majutsu koushi to akashic records","Sistine Fibel","Blanco","si",NULL, "sistine");
insert into characters VALUES("Mujer","Rokudenashi majutsu koushi to akashic records","Rumia Tingel","Rubio","si",NULL, "rumia");
insert into characters VALUES("Mujer","Rokudenashi majutsu koushi to akashic records","Re=L Rayford","Azul","si",NULL, "rayford");
insert into characters VALUES("Mujer","Rokudenashi majutsu koushi to akashic records","Celica Arfonia","Rubio","no",NULL, "celica");
insert into characters VALUES("Mujer","Oushitsu kyoushi Haine","Adele von Glanzreich","Rubio","si",NULL, "adele");
insert into characters VALUES("Mujer","Saenai heroine no sodatekata 2","Eriri Spencer Sawamura","Rubio","no",NULL, "eriri");
insert into characters VALUES("Mujer","Saenai heroine no sodatekata 2","Utaha Kasumigaoka","Negro","no",NULL, "utaha");
insert into characters VALUES("Mujer","Saenai heroine no sodatekata 2","Megumi Katou","Castanio","no",NULL, "megumi");
insert into characters VALUES("Mujer","Saenai heroine no sodatekata 2","Hyoudou Michiru","Morado","no",NULL, "hyoudou-michiru");
insert into characters VALUES("Mujer","Clockwork Planet","RyuZU","Blanco","no",NULL, "ryuzu");
insert into characters VALUES("Mujer","Clockwork Planet","Marie Bell Breguest","Rubio","si",NULL, "marie-bell");
insert into characters VALUES("Mujer","Clockwork Planet","AnchoR","Rubio","si",NULL, "anchor");
insert into characters VALUES("Mujer","Shingeki no kyojin 2","Ymir","Negro","no",NULL, "ymir");
insert into characters VALUES("Mujer","Shingeki no kyojin 2","MiKasa Ackerman","Negro","no",NULL, "mikasa");
insert into characters VALUES("Mujer","Shingeki no kyojin 2","Historia Reiss","Rubio","no",NULL, "historia");
insert into characters VALUES("Mujer","Shingeki no kyojin 2","Annie Leonhart","Rubio","no",NULL, "annie");
insert into characters VALUES("Mujer","Shingeki no kyojin 2","Hanji Zoe","Castanio","no",NULL, "hanji");
insert into characters VALUES("Mujer","Shingeki no kyojin 2","Sasha Blouse","Castanio","no",NULL, "sasha");
insert into characters VALUES("Mujer","Boku no hero 2","Ochako Uraraka","Castanio","no",NULL, "uraraka");
insert into characters VALUES("Mujer","Boku no hero 2","Momo Yaoyorozu","Negro","no",NULL, "yaoyorozu");
insert into characters VALUES("Mujer","Boku no hero 2","Tsuyu Asui","Verde","no",NULL, "tsuyu");
insert into characters VALUES("Mujer","Boku no hero 2","Kyoka Jiro","Morado","no",NULL, "kyoka");
insert into characters VALUES("Mujer","Boku no hero 2","Mina Ashido","Rosa","no",NULL, "mina-ashido");
insert into characters VALUES("Mujer","Boku no hero 2","Toru Hagakure","Invisible","no",NULL, "hagakure");
insert into characters VALUES("Mujer","Boku no hero 2","Itsuka Kendo","Naranja","no",NULL, "itsuka-kendo");
insert into characters VALUES("Mujer","Boku no hero 2","Ibara Shiozaki","Verde","no",NULL, "ibara-shiozaki");
insert into characters VALUES("Mujer","Boku no hero 2","Recovery Girl","Gris","no",NULL, "recovery");
insert into characters VALUES("Mujer","Boku no hero 2","Mei Hatsume","Rosa","no",NULL, "mei");
insert into characters VALUES("Mujer","Boku no hero 2","Mount Lady","Beige","no",NULL, "mount-lady");
insert into characters VALUES("Mujer","Eromanga-sensei","Megumi Jinno","Naranja","si",NULL, "magumi-jinno");
insert into characters VALUES("Mujer","Eromanga-sensei","Elf Yamada","Rubio","si",NULL, "elf-yamada");
insert into characters VALUES("Mujer","Eromanga-sensei","Tomoe Takasago","Negro","no",NULL, "tomoe-takasago");
insert into characters VALUES("Mujer","Eromanga-sensei","Muramasa Senju","Morado","no",NULL, "muramasa-senju");
insert into characters VALUES("Mujer","Eromanga-sensei","Ayame Kagurazaka","Castanio","no",NULL, "ayame-kagurazaka");
insert into characters VALUES("Mujer","Eromanga-sensei","Sagiri Izumi","Blanco","si",NULL, "sagiri");
insert into characters VALUES("Mujer","Re:Creators","Selesia Yupitiria","Rojo","no",NULL, "selesia");
insert into characters VALUES("Mujer","Re:Creators","Meteora Osterreich","Blanco","no",NULL, "meteora");
insert into characters VALUES("Mujer","Re:Creators","Alicetelia February","Rubio","no",NULL, "alicetelia");
insert into characters VALUES("Mujer","Re:Creators","Mamika Kirameki","Rosa","si",NULL, "mamika");
insert into characters VALUES("Mujer","Re:Creators","Magane Chikujoin","Morado","no",NULL, "magane");
insert into characters VALUES("Mujer","Re:Creators","Altair","Blanco","no",NULL, "altair");
insert into characters VALUES("Mujer","Re:Creators","Marine","Castanio","no",NULL, "marine");
insert into characters VALUES("Mujer","Alice to Zoroku","Sana Kashimura","Rubio","si",NULL, "sana");
insert into characters VALUES("Mujer","Alice to Zoroku","Sanae Kashimura","Castanio","si",NULL, "sanae");
insert into characters VALUES("Mujer","Alice to Zoroku","Asahi Hinagiri","Azul","si",NULL, "asahi");
insert into characters VALUES("Mujer","Alice to Zoroku","Yonaga Hinagiri","Azul","si",NULL, "yonaga");
insert into characters VALUES("Mujer","Alice to Zoroku","Shizuku Ichijo","Negro","no",NULL, "shizuku");
insert into characters VALUES("Mujer","Alice to Zoroku","Noriko Yamada","Castanio","no",NULL, "noriko");
insert into characters VALUES("Mujer","Alice to Zoroku","Miriam C. Tachibana","Castanio","no",NULL, "miriam");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Kirukiru Amo","Negro","no",NULL, "amo");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Rin Onigawara","Negro","si",NULL, "rin");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Mary Kikakujo","Rubio","si",NULL, "mary");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Warabi Hanasaka","Rubio","si",NULL, "warabi");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Satori Tamaba","Verde","si",NULL, "satori");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Tsukuyo Inaba","Blanco","si",NULL, "tsukuyo");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Nono Mozunono","Rosa","si",NULL, "nono");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Choka U. Barazaki","Rosa","si",NULL, "choka");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Sasa Kurasaki","Blanco","si",NULL, "sasa");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Ui Migii","Azul","si",NULL, "migii");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Tsunemi Toko","Castanio","si",NULL, "Tsunemi");
insert into characters VALUES("Mujer","Accel World","Burakku Rotasu","Negro","no",NULL, "Burakku");
insert into characters VALUES("Mujer","Accel World","Kurashima Chiyuri","Naranja","no",NULL, "Kurashima");
