insert into dates VALUES("Zero kara hajimeru mahou no sho","Abril","En emision","Primavera","2017","Lunes","Finalizado");
insert into dates VALUES("Rokudenashi majutsu koushi to akashic records","Abril","En emision","Primavera","2017","Martes","Finalizado");
insert into dates VALUES("Oushitsu kyoushi Haine","Abril","En emision","Primavera","2017","Martes","Finalizado");
insert into dates VALUES("Saenai heroine no sodatekata 2","Abril","En emision","Primavera","2017","Jueves","Finalizado");
insert into dates VALUES("Clockwork Planet","Abril","En emision","Primavera","2017","Jueves","Finalizado");
insert into dates VALUES("Shingeki no kyojin 2","Abril","En emision","Primavera","2017","Sabado","Finalizado");
insert into dates VALUES("Boku no hero 2","Abril","En emision","Primavera","2017","Sabado","Finalizado");
insert into dates VALUES("Eromanga-sensei","Abril","En emision","Primavera","2017","Sabado","Finalizado");
insert into dates VALUES("Re:Creators","Abril","En emision","Primavera","2017","Sabado","Finalizado");
insert into dates VALUES("Alice to Zoroku","Abril","En emision","Primavera","2017","Sabado","Finalizado");
insert into dates VALUES("Busou shoujo machiavellianism","Abril","En emision","Primavera","2017","Domingo","Finalizado");
insert into dates VALUES("Accel World","Abril","Septiembre","Primavera","2012","Finalizado","Finalizado");
insert into dates VALUES("Akame ga kill","Julio","Diciembre","Verano","2014","Finalizado","Finalizado");
insert into dates VALUES("Aho Girl","Junio","En emision","Verano","2017","Martes","Finalizado");
insert into dates VALUES("Tsurezure Children","Junio","En emision","Verano","2017","Martes","Finalizado");
insert into dates VALUES("Isekai Shoukudou","Junio","En emision","Verano","2017","Lunes","Finalizado");
insert into dates VALUES("Koi to Uso","Junio","En emision","Verano","2017","Lunes","Finalizado");
insert into dates VALUES("Keppeki Danshi! Aoyama-kun","Junio","En emision","Verano","2017","Domingo","Finalizado");
insert into dates VALUES("Kakegurui","Junio","En emision","Verano","2017","Sabado","Finalizado");
insert into dates VALUES("Akiba`s strip","Enero","Marzo","Invierno","2016","Miercoles","Finalizado");
insert into dates VALUES("Angel Beats","Abril","Junio","Primavera","2010","Sabado","Finalizado");
insert into dates VALUES("Another","Enero","Marzo","Invierno","2011","Lunes","Finalizado");
insert into dates VALUES("Assassination Classroom","Enero","Junio","Invierno","2014","Viernes","Finalizado");
insert into dates VALUES("Assassination Classroom 2","Enero","Junio","Invierno","2015","Jueves","Finalizado");
insert into dates VALUES("Baby princess 3d","Julio","Julio","Verano","2011","Miercoles","Finalizado");
insert into dates VALUES("Black Bullet","Abril","Julio","Primavera","2014","Martes","Finalizado");
insert into dates VALUES("Boku dake ga inai machi","Enero","Marzo","Invierno","2015","Viernes","Finalizado");
insert into dates VALUES("Boku no hero","Abril","Junio","Primavera","2016","Domingo","Finalizado");
insert into dates VALUES("Charlotte","Julio","Septiembre","Verano","2015","Sabado","Finalizado");
insert into dates VALUES("Choujingen game neptune","Julio","Septiembre","Verano","2013","Viernes","Finalizado");
insert into dates VALUES("Date a live","Abril","Junio","Primavera","2013","Sabado","Finalizado");
insert into dates VALUES("Date a live 2","Abril","Junio","Primavera","2014","Sabado","Finalizado");
insert into dates VALUES("Death parade","Enero","Marzo","Invierno","2014","Viernes","Finalizado");
insert into dates VALUES("Kono subarashii","Enero","Marzo","Invierno","2015","Miercoles","Finalizado");
insert into dates VALUES("Kono subarashii 2","Enero","Marzo","Invierno","2016","Jueves","Finalizado");
insert into dates VALUES("Gabriel Dropout","Enero","Marzo","Invierno","2016","Lunes","Finalizado");
insert into dates VALUES("Watamote","Julio","Septiembre","Verano","2013","Lunes","Finalizado");
insert into dates VALUES("Valkyrie Drive","Octubre","Diciembre","Otonio","2015","Sabado","Finalizado");
insert into dates VALUES("Kiss x sis","Abril","Junio","Primavera","2010","Domingo","Finalizado");
insert into dates VALUES("Kono Naka","Julio","Septiembre","Verano","2012","Viernes","Finalizado");
insert into dates VALUES("One Punch Man","Octubre","Diciembre","Otonio","2015","Lunes","Finalizado");
insert into dates VALUES("Monster Musume","Julio","Septiembre","Verano","2015","Martes","Finalizado");
insert into dates VALUES("Overloard","Julio","Septiembre","Verano","2015","Martes","Finalizado");
insert into dates VALUES("Sakamoto","Abril","Julio","Primavera","2016","Viernes","Finalizado");
insert into dates VALUES("Kabaneri","Abril","Junio","Primavera","2016","Viernes","Finalizado");
insert into dates VALUES("Kiniro Mosaic","Julio","Septiembre","Verano","2013","Sabado","Finalizado");
insert into dates VALUES("Dagashi Kashi","Enero","Marzo","Invierno","2016","Jueves","Finalizado");
insert into dates VALUES("Trinity Seven","Octubre","Diciembre","Otonio","2014","Martes","Finalizado");
insert into dates VALUES("Sword art online","Julio","Diciembre","Verano","2012","Sabado","Finalizado");
insert into dates VALUES("Sword art online 2","Julio","Diciembre","Verano","2014","Sabado","Finalizado");
insert into dates VALUES("Shimoneta","Julio","Septiembre","Verano","2015","Sabado","Finalizado");
insert into dates VALUES("Sankarea","Abril","Junio","Primavera","2012","Jueves","Finalizado");
insert into dates VALUES("Mirai Nikki","Octubre","Abril","Otonio","2011","Domingo","Finalizado");
insert into dates VALUES("Rewrite","Julio","Septiembre","Verano","2016","Sabado","Finalizado");
insert into dates VALUES("Rewrite:Moon and terra","Enero","Marzo","Invierno","2016","Sabado","Finalizado");
insert into dates VALUES("Re:Zero","Abril","Septiembre","Primavera","2016","Lunes","Finalizado");
insert into dates VALUES("Rampo Kitan: Game of Laplace","Enero","Septiembre","Verano","2015","Jueves","Finalizado");
insert into dates VALUES("Outbreak Company","Octubre","Diciembre","Otonio","2013","Jueves","Finalizado");
insert into dates VALUES("Punchline","Abril","Junio","Primavera","2015","Jueves","Finalizado");
insert into dates VALUES("Prison school","Julio","Septiembre","Verano","2015","Viernes","Finalizado");
insert into dates VALUES("Machine Doll wa Kizutsukanai","Octubre","Diciembre","Otonio","2013","Lunes","Finalizado");
insert into dates VALUES("Noragami","Octubre","Diciembre","Otonio","2015","Viernes","Finalizado");
insert into dates VALUES("Noragami Aragoto","Octubre","Diciembre","Otonio","2015","Sabado","Finalizado");
insert into dates VALUES("Osomatsu-san","Octubre","Marzo","Otonio","2015","Domingo","Finalizado");
insert into dates VALUES("Sakura-so no Pet na Kanojo","Octubre","Marzo","Otonio","2012","Martes","Finalizado");
insert into dates VALUES("Seirei Tsukai no Bladedance","Julio","Septiembre","Verano","2014","Lunes","Finalizado");
insert into dates VALUES("No game No Life","Abril","Junio","Primavera","2014","Miercoles","Finalizado");
insert into dates VALUES("Netoge no Yome wa Onna","Abril","Junio","Primavera","2016","Jueves","Finalizado");
insert into dates VALUES("Ore ga Ojo-sama Gakko","Octubre","Diciembre","Otonio","2015","Miercoles","Finalizado");
insert into dates VALUES("Yamada-kun to 7-nin no Majo","Abril","Junio","Primavera","2015","Domingo","Finalizado");
insert into dates VALUES("Plastic Nee-san","Mayo","Julio","Primavera","2012","Miercoles","Finalizado");
insert into dates VALUES("Shokugeki no Soma","Abril","Septiembre","Primavera","2015","Viernes","Finalizado");
insert into dates VALUES("Shokugeki no Souma: Ni no Sara","Julio","Septiembre","Verano","2016","Sabado","Finalizado");
insert into dates VALUES("Kuroko no basket","Abril","Septiembre","Primavera","2012","Sabado","Finalizado");
insert into dates VALUES("Kuroko no basket 2","Octubre","Marzo","Otonio","2013","Sabado","Finalizado");
insert into dates VALUES("Kuroko no basket 3","Enero","Junio","Invierno","2014","Sabado","Finalizado");
insert into dates VALUES("Shingeki no Kyojin","Abril","Septiembre","Primavera","2013","Sabado","Finalizado");
insert into dates VALUES("High School DxD","Enero","Marzo","Invierno","2012","Viernes","Finalizado");
insert into dates VALUES("High School DxD New","Julio","Septiembre","Verano","2013","Domingo","Finalizado");
insert into dates VALUES("High School DxD Born","Abril","Junio","Primavera","2015","Sabado","Finalizado");
insert into dates VALUES("Dakara Boku wa, H ga Dekinai","Julio","Septiembre","Verano","2012","Viernes","Finalizado");
insert into dates VALUES("Tokyo Ghoul","Julio","Septiembre","Verano","2014","Viernes","Finalizado");
insert into dates VALUES("Tokyo Ghoul 2","Enero","Marzo","Invierno","2014","Jueves","Finalizado");
insert into dates VALUES("Hai to Gensou no Grimgar","Enero","Marzo","Invierno","2015","Lunes","Finalizado");
insert into dates VALUES("Hentai Oji to Warawanai Neko","Abril","Junio","Primavera","2013","Sabado","Finalizado");
insert into dates VALUES("Gakko Gurashi","Julio","Septiembre","Verano","2015","Jueves","Finalizado");
insert into dates VALUES("Gakusen Toshi Asterisk","Octubre","Diciembre","Otonio","2015","Sabado","Finalizado");
insert into dates VALUES("Gakusen Toshi Asterisk 2","Abril","Junio","Primavera","2016","Sabado","Finalizado");
insert into dates VALUES("Boku wa Tomodachi ga Sukunai","Octubre","Diciembre","Otonio","2011","Viernes","Finalizado");
insert into dates VALUES("Boku wa Tomodachi ga Sukunai next","Enero","Marzo","Invierno","2013","Viernes","Finalizado");
insert into dates VALUES("Sora no otoshimono","Octubre","Diciembre","Otonio","2009","Domingo","Finalizado");
insert into dates VALUES("Sora no otoshimono:Forte","Octubre","Diciembre","Otonio","2010","Viernes","Finalizado");
insert into dates VALUES("Shinmai Maou no Testament","Enero","Marzo","Invierno","2014","Miercoles","Finalizado");
insert into dates VALUES("Shinmai Maou no Testament Burst","Octubre","Diciembre","Otonio","2015","Martes","Finalizado");
insert into dates VALUES("Saenai heroine no sodatekata","Enero","Marzo","Invierno","2014","Viernes","Finalizado");
insert into dates VALUES("Masamune-kun no Revenge","Enero","Marzo","Invierno","2016","Jueves","Finalizado");
insert into dates VALUES("Selector infected","Abril","Junio","Primavera","2014","Jueves","Finalizado");
insert into dates VALUES("Selector Spread Wixoss","Octubre","Diciembre","Otonio","2014","Viernes","Finalizado");
insert into dates VALUES("Lostorage incited Wixoss","Octubre","Diciembre","Otonio","2016","Sabado","Finalizado");
insert into dates VALUES("Highschool of the dead","Julio","Septiembre","Verano","2010","Lunes","Finalizado");
insert into dates VALUES("Himouto! Umaru-chan","Julio","Septiembre","Verano","2015","Lunes","Finalizado");
insert into dates VALUES("Urara Meirocho","Enero","Marzo","Invierno","2016","Jueves","Finalizado");
insert into dates VALUES("Musaigen no Phantom World","Enero","Marzo","Invierno","2015","Jueves","Finalizado");
insert into dates VALUES("Haruchika","Enero","Marzo","Invierno","2016","Miercoles","Finalizado");
insert into dates VALUES("Mob Psycho 100","Julio","Septiembre","Verano","2016","Martes","Finalizado");
insert into dates VALUES("Denpa Onna to Seishun Otoko","Abril","Julio","Primavera","2011","Viernes","Finalizado");
insert into dates VALUES("Boruto","Abril","","Primavera","2017","Miercoles","Finalizado");
insert into dates VALUES("Chunibyo Demo Koi ga Shitai!","Octubre","Diciembre","Otonio","2012","Jueves","Finalizado");
insert into dates VALUES("Chunibyo Demo Koi ga Shitai Ren!","Enero","Marzo","Invierno","2013","Miercoles","Finalizado");
insert into dates VALUES("Flip Flappers","Octubre","Diciembre","Otonio","2016","Jueves","Finalizado");
insert into dates VALUES("Kuzu no Honkai","Enero","Marzo","Invierno","2016","Jueves","Finalizado");
insert into dates VALUES("Okami-san to Shichinin no Nakama-tachi","Julio","Septiembre","Verano","2010","Jueves","Finalizado");
insert into dates VALUES("Dragon ball","Febrero","Abril","Invierno","1986","Martes","Finalizado");
insert into dates VALUES("Dragon ball Z","Abril","Enero","Primavera","1989","Miercoles","Finalizado");
insert into dates VALUES("Dragon ball super","Julio","","Verano","2015","Domingo","Finalizado");
insert into dates VALUES("Dragon ball GT","Febrero","Noviembre","Invierno","1996","Miercoles","Finalizado");
insert into dates VALUES("Little Witch Academia","Enero","Junio","Invierno","2016","Domingo","Finalizado");
insert into dates VALUES("Nagi no Asukara","Octubre","Abril","Otonio","2013","Jueves","Finalizado");
insert into dates VALUES("Made in abyss","Julio","","Verano","2017","Sabado","Finalizado");
insert into dates VALUES("Kore wa Zombie Desu ka?","Enero","Marzo","Invierno","2010","Martes","Finalizado");
insert into dates VALUES("Kore wa Zombie Desu ka? of the dead","Abril","Junio","Primavera","2012","Viernes","Finalizado");
insert into dates VALUES("18IF","Julio","","Verano","2017","Viernes","Finalizado");
insert into dates VALUES("Konbini Kareshi","Julio","","Verano","2017","Jueves","Finalizado");
insert into dates VALUES("Hajimete no gal","Julio","","Verano","2017","Miercoles","Finalizado");
insert into dates VALUES("Isekai wa smartphone to tomo ni","Julio","","Verano","2017","Martes","Finalizado");
insert into dates VALUES("Princess Principal","Julio","","Verano","2017","Lunes","Finalizado");
insert into dates VALUES("Gamers","Julio","","Verano","2017","Jueves","Finalizado");
insert into dates VALUES("Tenshi no 3P","Julio","","Verano","2017","Lunes","Finalizado");
insert into dates VALUES("Youkoso Jitsutyoku Shijou Shugi no Kyoushitsu e","Julio","","Verano","2017","Miercoles","Finalizado");

insert into dates VALUES("Omiai Aite Wa Oshiego","Octubre","","Otonio","2017","Lunes","");
insert into dates VALUES("Himouto! Umaru-chan R","Octubre","","Otonio","2017","Domingo","");
insert into dates VALUES("Shoujo Shuumatsu Ryokou","Octubre","","Otonio","2017","Viernes","");
insert into dates VALUES("Osomatsu-san 2","Octubre","","Otonio","2017","Lunes","");
insert into dates VALUES("Imouto sae ireba II","Octubre","","Otonio","2017","Lunes","");





/*----------------------POR METER EN LAS OTRAS TABLAS--------------------*/
