/*-------------------------- 2017-------------------------*/
/*NOMBRE	TEMPORADA	DESCRIPCION	NOTA	CAPITULOS*/
insert into ANIMES VALUES("Zero kara hajimeru mahou no sho","1","Bruja rengar blanco","10"," 8","zero-kara-hajimeru-mahou-no-sho");
insert into ANIMES VALUES("Rokudenashi majutsu koushi to akashic records","1","Best uniforme of anime","10"," 8","rokudenashi-majutsu-koushi-to-akashic-records");
insert into ANIMES VALUES("Oushitsu kyoushi Haine","1",	"Tutor real"," 9"," 7","oushitsu-kyoushi-haine");
insert into ANIMES VALUES("Saenai heroine no sodatekata 2","2",	"Crear juego"," 8","12","saenai-heroine-no-sodatekata-2");
insert into ANIMES VALUES("Clockwork Planet","1","Mundo de relojes","10","12","clockwork-planet");
insert into ANIMES VALUES("Shingeki no kyojin 2","2","Mikasa","10","12","shingeki-no-kyojin-2");
insert into ANIMES VALUES("Boku no hero 2","2","All Might","10","12","boku-no-hero-academia-2nd-season");
insert into ANIMES VALUES("Eromanga-sensei","1","Hermana dibuja ero"," 9","12","eromanga-sensei");
insert into ANIMES VALUES("Re:Creators","1","Fuera de su anime"," 7","12","re-creators");
insert into ANIMES VALUES("Alice to Zoroku","1","lolis poderes","10","12","alice-to-zouroku");
insert into ANIMES VALUES("Busou shoujo machiavellianism","1","peli verde super kawaii","10","12","busou-shoujo-machiavellianism");
insert into ANIMES VALUES("Accel World","1","Prota cerdito"," 7","12","accel-world");
insert into ANIMES VALUES("Akame ga kill","1","Prota no es prota"," 7","12","akame-ga-kill");
insert into ANIMES VALUES("Aho Girl","1","Loca platanos"," 8","1","aho-girl");
insert into ANIMES VALUES("Tsurezure Children","1","Declaraciones"," 7","1","tsurezure-children");
insert into ANIMES VALUES("Isekai Shoukudou","1","Restaurante universal","7","1","isekai-shokudou");
insert into ANIMES VALUES("Koi to Uso","1","Amor prohibido","9","1","koi-to-uso");
insert into ANIMES VALUES("Keppeki Danshi! Aoyama-kun","1","Futbolista limpiador","8","1","keppeki-danshi-aoyama-kun");
insert into ANIMES VALUES("Kakegurui","1","Copia no game no life","8","1","kakegurui");
insert into ANIMES VALUES("Akiba`s strip","1","Quitar ropa para ganar"," 8","12","akiba-s-trip-the-animation");
insert into ANIMES VALUES("Angel Beats","1","Loli programadora"," 8","12","angel-beats");
insert into ANIMES VALUES("Another","1","Chica parche","10","12","another");
insert into ANIMES VALUES("Assassination Classroom","1","Koro-sensei"," 9","24","ansatsu-kyoushitsu");
insert into ANIMES VALUES("Assassination Classroom 2","2","Koro-sensei"," 8","24","ansatsu-kyoushitsu-2nd-season");
insert into ANIMES VALUES("Baby princess 3d","1","harem 1 capitulo"," 7"," -1","baby-princess-3d-paradise-love");
insert into ANIMES VALUES("Black Bullet","1","lolis para todos"," 7"," 1","black-bullet");
insert into ANIMES VALUES("Boku dake ga inai machi","1","Volver al pasado"," 9"," 1","boku-dake-ga-inae-machi");
insert into ANIMES VALUES("Boku no hero","1","All Might","10","12","boku-no-hero-academia");
insert into ANIMES VALUES("Charlotte","1","Chicos con poderes",	" 8","13","charlotte");
insert into ANIMES VALUES("Choujingen game neptune","1","Diosas lolis","10","13","choujigen-game-neptune-the-animation");
insert into ANIMES VALUES("Date a live","1","Preguntas"," 7","12","date-a-live");
insert into ANIMES VALUES("Date a live 2","2","Kurumi"," 8","12","date-a-live-ii");
insert into ANIMES VALUES("Death parade","1","Pruebas muerte"," 9","12","death-parade");
insert into ANIMES VALUES("Kono subarashii","1","Diosa inutil","10","10","kono-subarashii-sekai-ni-shukufuku-wo");
insert into ANIMES VALUES("Kono subarashii 2","2","Rival megumi","10","10","kono-subarashii-sekai-ni-shukufuku-wo-2");
insert into ANIMES VALUES("Gabriel Dropout","1","Ángel caido","7","12","gabriel-dropout");
insert into ANIMES VALUES("Watamote","1","Chica Hikikiomori","9","12","watamote");
insert into ANIMES VALUES("Valkyrie Drive","1","Chicas isla","8","12","valkyrie-drive-mermaid");
insert into ANIMES VALUES("Kiss x sis","1","Hermanas","9","12","kissxsis");
insert into ANIMES VALUES("Kono Naka","1","Hermana sorpresa","7","12","kono-naka-ni-hitori-imouto-ga-iru");
insert into ANIMES VALUES("One Punch Man","1","Saitama","10","12","one-punch-man");
insert into ANIMES VALUES("Monster Musume","1","suu","10","12","monster-musume-no-iru-nichijou");
insert into ANIMES VALUES("Overloard","1","Atrapado en un juego","9","13","overlord");
insert into ANIMES VALUES("Sakamoto","1","PUTO AMO","7","12","sakamoto-desu-ga");
insert into ANIMES VALUES("Kabaneri","1","zombies titanes","10","13","koutetsujou-no-kabaneri");
insert into ANIMES VALUES("Kiniro Mosaic","1","Karen desu","8","12","kiniro-mosaic");
insert into ANIMES VALUES("Dagashi Kashi","1","Loca de los dulces","7","12","dagashi-kashi");
insert into ANIMES VALUES("Trinity Seven","1","No princeso","8","12","trinity-seven");
insert into ANIMES VALUES("Sword art online","1","Kirito","8","25","sword-art-online");
insert into ANIMES VALUES("Sword art online 2","2","Kirito","4","24","sword-art-online-ii");
insert into ANIMES VALUES("Shimoneta","1","agujero misterioso","8","12","shimoneta");
insert into ANIMES VALUES("Sankarea","1","Novia Zombie","6","12","sankarea");
insert into ANIMES VALUES("Mirai Nikki","1","yuki yuki","10","26","mirai-nikki");
insert into ANIMES VALUES("Rewrite","1","oppais oculto","10","13","rewrite");
insert into ANIMES VALUES("Rewrite:Moon and terra","2","oppais oculto","10","11","rewrite-moon-and-terra");
insert into ANIMES VALUES("Re:Zero","1","Rem Rem","10","25","re-zero-kara-hajimeru-isekai-seikatsu");
insert into ANIMES VALUES("Rampo Kitan: Game of Laplace","1","Calculo matemático","8","11",NULL);
insert into ANIMES VALUES("Outbreak Company","1","Reina loli","8","12","outbreak-company");
insert into ANIMES VALUES("Punchline","1","Gemidos","7","12","punch-line");
insert into ANIMES VALUES("Prison school","1","Carcel","10","12","prison-school");
insert into ANIMES VALUES("Machine Doll wa Kizutsukanai","1","Waifu","8","12","machine-doll-wa-kizutsukanai");
insert into ANIMES VALUES("Noragami","1","Dios pobre","9","12","noragami");
insert into ANIMES VALUES("Noragami Aragoto","2","Dios pobre","8","13","noragami-aragoto");
insert into ANIMES VALUES("Osomatsu-san","1","Novita","10","25","osomatsu-san");
insert into ANIMES VALUES("Sakura-so no Pet na Kanojo","1","Sakura-so","10","24","sakurasou-no-pet-na-kanojo");
insert into ANIMES VALUES("Seirei Tsukai no Bladedance","1","loli de fuego","10","12","seirei-tsukai-no-blade-dance");
insert into ANIMES VALUES("No Game No Life","1","Shiro y Sora","10","12","no-game-no-life");
insert into ANIMES VALUES("Netoge no Yome wa Onna","1","Ako","8","12","netoge-no-yome-wa-onnanoko-ja-nai-to-omotta");
insert into ANIMES VALUES("Ore ga Ojo-sama Gakko","1","Musculos","8","12","ore-ga-ojousama");
insert into ANIMES VALUES("Yamada-kun to 7-nin no Majo","1","Besos con brujas","9","12","yamada-kun-to-7-nin-no-majo");
insert into ANIMES VALUES("Plastic Nee-san","1","Serie corta","9","12","plastic-neesan");
insert into ANIMES VALUES("Shokugeki no Soma","1","Cocina","10","24","shokugeki-no-soma");
insert into ANIMES VALUES("Shokugeki no Souma: Ni no Sara","2","Cocina","9","13","shokugeki-no-souma-ni-no-sara");
insert into ANIMES VALUES("Kuroko no basket","1","Baloncesto","10","25","kuroko-no-basket");
insert into ANIMES VALUES("Kuroko no basket 2","2","Baloncesto","10","25","kuroko-no-basket-2");
insert into ANIMES VALUES("Kuroko no basket 3","3","Baloncesto","10","25","kuroko-no-basket-3");
insert into ANIMES VALUES("Shingeki no Kyojin","1","Titanes","10","25","shingeki-no-kyojin");
insert into ANIMES VALUES("High School DxD","1","Rias Gremory","10","12","high-school-dxd");
insert into ANIMES VALUES("High School DxD New","2","Rias Gremory","10","12","high-school-dxd-new");
insert into ANIMES VALUES("High School DxD Born","3","Rias Gremory","10","13","high-school-dxd-born");
insert into ANIMES VALUES("Dakara Boku wa, H ga Dekinai","1","hermano issei","7","12","dakara-boku-wa-h-ga-dekinai");
insert into ANIMES VALUES("Tokyo Ghoul","1","Comer humanos","9","12","tokyo-ghoul");
insert into ANIMES VALUES("Tokyo Ghoul 2","2","Comer humanos","6","12","tokyo-ghoul-a");
insert into ANIMES VALUES("Hai to Gensou no Grimgar","1","Bichos sufren","9","12","hai-to-gensou-no-grimgar");
insert into ANIMES VALUES("Hentai Oji to Warawanai Neko","1","Gato suerte","8","12","hentai-ouji-to-warawanai-neko");
insert into ANIMES VALUES("Kore wa Zombie Desu ka?","1","Yuu","7","12","kore-wa-zombie-desu-ka");
insert into ANIMES VALUES("Kore wa Zombie Desu ka? of the dead","2","Yuu","7","10","kore-wa-zombie-desu-ka-of-the-dead");
insert into ANIMES VALUES("Gakko Gurashi","1","Zombies vs Lolis","9","12",NULL);
insert into ANIMES VALUES("Gakusen Toshi Asterisk","1","Escuela de pelea","8","12",NULL);
insert into ANIMES VALUES("Gakusen Toshi Asterisk 2","2","Escuela de pelea","9","13",NULL);
insert into ANIMES VALUES("Boku wa Tomodachi ga Sukunai","1","Club de los vecinos","8","12",NULL);
insert into ANIMES VALUES("Boku wa Tomodachi ga Sukunai next","2","Club de los vecinos","8","12",NULL);
insert into ANIMES VALUES("Sora no otoshimono","1","Angeles","8","12","sora-no-otoshimono");
insert into ANIMES VALUES("Sora no otoshimono:Forte","2","Angeles","8","12","sora-no-otoshimono-forte");
insert into ANIMES VALUES("Shinmai Maou no Testament","1","Como DxD","7","13","shinmai-maou-no-testament");
insert into ANIMES VALUES("Shinmai Maou no Testament Burst","2","Como DxD","7","11","shinmai-maou-no-testament-burst");
insert into ANIMES VALUES("Saenai heroine no sodatekata","1","Crear juego"," 10","13","saenai-heroine-no-sodatekata");
insert into ANIMES VALUES("Masamune-kun no Revenge","1","Venganza por amor"," 8","12","saenai-heroine-no-sodatekata-2");
insert into ANIMES VALUES("Selector infected","1","Juego de cartas"," 9","12",NULL);
insert into ANIMES VALUES("Selector Spread Wixoss","2","Juego de cartas"," 8","12",NULL);
insert into ANIMES VALUES("Lostorage incited Wixoss","3","Juego de cartas"," 8","12","lostorage-incited-wixoss");
insert into ANIMES VALUES("Highschool of the dead","1","Zombies"," 9","12","high-school-of-the-dead");
insert into ANIMES VALUES("Himouto! Umaru-chan","1","hamster"," 9","12","himouto-umaru-chan");
insert into ANIMES VALUES("Urara Meirocho","1","Road to bruja"," 7","12","himouto-umaru-chan-r");
insert into ANIMES VALUES("Musaigen no Phantom World","1","Mundo con poderes"," 6","13","musaigen-no-phantom-world");
insert into ANIMES VALUES("Lance N' Masques","1","Caballeros"," 8","12","lance-n-masques");
insert into ANIMES VALUES("Haruchika","1","Chica flauta detective"," 7","12","haruchika-haruta-to-chika-wa-seishun-suru");
insert into ANIMES VALUES("Mob Psycho 100","1","guiños saitama"," 7","12","mob-psycho-100");
insert into ANIMES VALUES("Denpa Onna to Seishun Otoko","1","Chica ovni"," 8","12","denpa-onna-to-seishun-otoko");
insert into ANIMES VALUES("Boruto","1","Naruto falso"," 6","12","boruto-naruto-next-generations");
insert into ANIMES VALUES("Chunibyo Demo Koi ga Shitai!","1","Ojo malvado"," 8","12","chuunibyou-demo-koi-ga-shitai");
insert into ANIMES VALUES("Chunibyo Demo Koi ga Shitai Ren!","2","Ojo malvado"," 7","12","chuunibyou-demo-koi-ga-shitai-ren");
insert into ANIMES VALUES("Flip Flappers","1","Ojos grandes"," 7","12","flip-flappers");
insert into ANIMES VALUES("Kuzu no Honkai","1","Amigos con derecho"," 9","12","kuzu-no-honkai");
insert into ANIMES VALUES("Okami-san to Shichinin no Nakama-tachi","1","Favor por favor"," 7","12","ookami-san-to-shichinin-no-nakama-tachi");
insert into ANIMES VALUES("Dragon ball","1","koku niño"," 7","153","dragon-ball");
insert into ANIMES VALUES("Dragon ball Z","2","Koku saiyan"," 9","291","dragon-ball-z");
insert into ANIMES VALUES("Dragon ball super","3","Koku dios"," 8","100","dragon-ball-super");
insert into ANIMES VALUES("Dragon ball GT","4","Koku niño 2"," 6","64","dragon-ball-gt");
insert into ANIMES VALUES("Little Witch Academia","1","Road to bruja"," 10","24","little-witch-academia");
insert into ANIMES VALUES("Nagi no Asukara","1","Amor bajo el agua"," 8","26","nagi-no-asukara");
insert into ANIMES VALUES("Made in abyss","1","Grieta","10","1","made-in-abyss");
insert into ANIMES VALUES("Knight`s & Magic","1","Programador mecha","9","2","knight-s-magic");
insert into ANIMES VALUES("18IF","1","Juego sueño brujas","10","1","18if");
insert into ANIMES VALUES("Konbini Kareshi","1","Chica timida","7","1","konbini-kareshi");
insert into ANIMES VALUES("Hajimete no gal","1","echii gratuito","8","1","hajimete-no-gal");
insert into ANIMES VALUES("Isekai wa smartphone to tomo ni","1","re:zero + konosuba","10","1","isekai-wa-smartphone-to-tomo-ni");
insert into ANIMES VALUES("Princess Principal","1","Espias y ninjas lolis","10","1","princess-principal");
insert into ANIMES VALUES("Gamers","1","chica gamer","8","1","gamers");
insert into ANIMES VALUES("Tenshi no 3P","1","loli pop","8","1","tenshi-no-3p");
insert into ANIMES VALUES("Youkoso Jitsutyoku Shijou Shugi no Kyoushitsu e","1","Escuela de elite","9","1","youkoso-jitsuryoku-shijou-shugi-no-kyoushitsu-e");

insert into ANIMES VALUES("Omiai Aite Wa Oshiego","1","Profe - Alumno","6","2","omiai-aite-wa-oshiego-tsuyokina-mondaiji");
insert into ANIMES VALUES("Himouto! Umaru-chan R","2","hamster"," 9","1","himouto-umaru-chan-r");
insert into ANIMES VALUES("Shoujo Shuumatsu Ryokou","1","2 supervivientes"," 9","1","shoujo-shuumatsu-ryokou");
insert into ANIMES VALUES("Osomatsu-san 2","2","Novita","10","2","osomatsu-san-2");

/*----------------------POR METER EN LAS OTRAS TABLAS--------------------*/
