insert into characters VALUES("Mujer","Zero kara hajimeru mahou no sho","Zero","Blanco","no");
insert into characters VALUES("Mujer","Zero kara hajimeru mahou no sho","Albus","Rubio","no");
insert into characters VALUES("Mujer","Rokudenashi majutsu koushi to akashic records","Sistine Fibel","Blanco","si");
insert into characters VALUES("Mujer","Rokudenashi majutsu koushi to akashic records","Rubio Tingel","Rubio","si");
insert into characters VALUES("Mujer","Rokudenashi majutsu koushi to akashic records","Re=L Rayford","Azul","si");
insert into characters VALUES("Mujer","Rokudenashi majutsu koushi to akashic records","Celica Arfonia","Rubio","no");
insert into characters VALUES("Mujer","Oushitsu kyoushi Haine","Adele von Glanzreich","Rubio","si");
insert into characters VALUES("Mujer","Saenai heroine no sodatekata 2","Eriri Spencer Sawamura","Rubio","no");
insert into characters VALUES("Mujer","Saenai heroine no sodatekata 2","Utaha Kasumigaoka","Negro","no");
insert into characters VALUES("Mujer","Saenai heroine no sodatekata 2","Megumi Katou","Castanio","no");
insert into characters VALUES("Mujer","Saenai heroine no sodatekata 2","Hyoudou Michiru","Morado","no");
insert into characters VALUES("Mujer","Clockwork Planet","RyuZU","Blanco","no");
insert into characters VALUES("Mujer","Clockwork Planet","Marie Bell Breguest","Rubio","si");
insert into characters VALUES("Mujer","Clockwork Planet","AnchoR","Rubio","si");
insert into characters VALUES("Mujer","Shingeki no kyojin 2","Ymir","Negro","no");
insert into characters VALUES("Mujer","Shingeki no kyojin 2","MiKasa Ackerman","Negro","no");
insert into characters VALUES("Mujer","Shingeki no kyojin 2","Historia Reiss","Rubio","no");
insert into characters VALUES("Mujer","Shingeki no kyojin 2","Annie Leonhart","Rubio","no");
insert into characters VALUES("Mujer","Shingeki no kyojin 2","Hanji Zoe","Castanio","no");
insert into characters VALUES("Mujer","Shingeki no kyojin 2","Sasha Blouse","Castanio","no");
insert into characters VALUES("Mujer","Boku no hero 2","Ochako Uraraka","Castanio","no");
insert into characters VALUES("Mujer","Boku no hero 2","Momo Yaoyorozu","Negro","no");
insert into characters VALUES("Mujer","Boku no hero 2","Tsuyu Asui","Verde","no");
insert into characters VALUES("Mujer","Boku no hero 2","Kyoka Jiro","Morado","no");
insert into characters VALUES("Mujer","Boku no hero 2","Mina Ashido","Rosa","no");
insert into characters VALUES("Mujer","Boku no hero 2","Toru Hagakure","Invisible","no");
insert into characters VALUES("Mujer","Boku no hero 2","Itsuka Kendo","Naranja","no");
insert into characters VALUES("Mujer","Boku no hero 2","Ibara Shiozaki","Verde","no");
insert into characters VALUES("Mujer","Boku no hero 2","Recovery Girl","Gris","no");
insert into characters VALUES("Mujer","Boku no hero 2","Mei Hatsume","Rosa","no");
insert into characters VALUES("Mujer","Boku no hero 2","Mount Lady","Beige","no");
insert into characters VALUES("Mujer","Eromanga-sensei","Megumi Jinno","Naranja","si");
insert into characters VALUES("Mujer","Eromanga-sensei","Elf Yamada","Rubio","si");
insert into characters VALUES("Mujer","Eromanga-sensei","Tomoe Takasago","Negro","no");
insert into characters VALUES("Mujer","Eromanga-sensei","Muramasa Senju","Morado","no");
insert into characters VALUES("Mujer","Eromanga-sensei","Ayame Kagurazaka","Castanio","no");
insert into characters VALUES("Mujer","Eromanga-sensei","Sagiri Izumi","Blanco","si");
insert into characters VALUES("Mujer","Re:Creators","Selesia Yupitiria","Rojo","no");
insert into characters VALUES("Mujer","Re:Creators","Meteora Osterreich","Blanco","no");
insert into characters VALUES("Mujer","Re:Creators","Alicetelia February","Rubio","no");
insert into characters VALUES("Mujer","Re:Creators","Mamika Kirameki","Rosa","si");
insert into characters VALUES("Mujer","Re:Creators","Magane Chikujoin","Morado","no");
insert into characters VALUES("Mujer","Re:Creators","Altair","Blanco","no");
insert into characters VALUES("Mujer","Re:Creators","Marine","Castanio","no");
insert into characters VALUES("Mujer","Alice to Zoroku","Sana Kashimura","Rubio","si");
insert into characters VALUES("Mujer","Alice to Zoroku","Sanae Kashimura","Castanio","si");
insert into characters VALUES("Mujer","Alice to Zoroku","Asahi Hinagiri","Azul","si");
insert into characters VALUES("Mujer","Alice to Zoroku","Yonaga Hinagiri","Azul","si");
insert into characters VALUES("Mujer","Alice to Zoroku","Shizuku Ichijo","Negro","no");
insert into characters VALUES("Mujer","Alice to Zoroku","Noriko Yamada","Castanio","no");
insert into characters VALUES("Mujer","Alice to Zoroku","Miriam C. Tachibana","Castanio","no");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Kirukiru Amo","Negro","no");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Rin Onigawara","Negro","si");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Mary Kikakujo","Rubio","si");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Warabi Hanasaka","Rubio","si");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Satori Tamaba","Verde","si");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Tsukuyo Inaba","Blanco","si");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Nono Mozunono","Rosa","si");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Choka U. Barazaki","Rosa","si");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Sasa Kurasaki","Blanco","si");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Ui Migii","Azul","si");
insert into characters VALUES("Mujer","Busou shoujo machiavellianism","Tsunemi Toko","Castanio","si");
insert into characters VALUES("Mujer","Accel World","Burakku Rotasu","Negro","no");
insert into characters VALUES("Mujer","Accel World","Kurashima Chiyuri","Naranja","no");
