DROP DATABASE IF EXISTS REGISTRO;

	CREATE DATABASE REGISTRO;

	USE REGISTRO

DROP TABLE IF EXISTS USUARIOS;

CREATE TABLE USUARIOS(

	id integer NOT NULL AUTO_INCREMENT,
	nombre varchar(15) NOT NULL,
	pass varchar(32) NOT NULL,
	correo varchar(50) NOT NULL,
	hora datetime NOT NULL,
	PRIMARY KEY(id)

);
